#! /usr/bin/env python
import sys
import json

if __name__ == "__main__":
    # the configuration.json file is passed in
    # as a first argument to all bake-scripts
    config_file = sys.argv[1]

    # read the config file and load it into
    # into a python dictionary
    config = json.load(open(config_file))

    configuration = config.get("configuration").copy()
    configuration.update(config.get("secure_configuration"))
    
    with open("/etc/rmp-prerecord-schedule/configuration.sh", 'wb') as fh:
      for key in configuration:
        if configuration.get(key):
          fh.write("export " + key.upper() + '="' + configuration.get(key) + "\"\n")
